name: SLSA generic generator for FurniWeb

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digests: ${{ steps.hash.outputs.digests }}

    steps:
      - uses: actions/checkout@v4

      - name: Build artifacts
        run: |
          echo "furniweb-artifact1" > artifact1.txt
          echo "furniweb-artifact2" > artifact2.txt

      - name: Generate subject for provenance
        id: hash
        run: |
          set -euo pipefail
          files=$(ls artifact*.txt)
          echo "hashes=$(sha256sum $files | base64 -w0)" >> "${GITHUB_OUTPUT}"

  provenance:
    needs: [build]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.4.0
    with:
      base64-subjects: "${{ needs.build.outputs.digests }}"
      upload-assets: true
